version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: webserver/Dockerfile
    ports:
      - "8000:8000"
    # For USB device access (CANable)
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    restart: unless-stopped

  # Future: Add frontend service here
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
